server:
  port: 8083

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSGTRES_PORT:5432}/${POSTGRES_DB:topic_service}
    username: postgres
    password: postgres
